const FETCH_ALL_AIRPORTS_SUCCESS = 'FETCH_ALL_AIRPORTS_SUCCESS';
const FETCH_ALL_AIRPORTS_ERROR = 'FETCH_ALL_AIRPORTS_ERROR';
const LOADING_AIRPORTS = 'LOADING_AIRPORTS';
const FILTER_AIRPORTS_SUCCESS = 'FILTER_AIRPORTS_SUCCESS';
const LOAD_MORE_SUCCESS = 'LOAD_MORE_SUCCESS';

export {
    FETCH_ALL_AIRPORTS_SUCCESS,
    FETCH_ALL_AIRPORTS_ERROR,
    LOADING_AIRPORTS,
    FILTER_AIRPORTS_SUCCESS,
    LOAD_MORE_SUCCESS
}